[tool.poetry]
name = "scenic"
version = "1.1.0b1"
description = "foo"
authors = ["Daniel Fremont <dfremont@ucsc.edu>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.6"
dotmap = "^1.3.13"
shapely = "^1.7.0"
pypoly2tri = "^0.0.3"
matplotlib = "^3.2.1"
scipy = "^1.4.1"
antlr4-python3-runtime = "^4.8"
opencv-python = "^4.2.0"
numpy = "^1.18.2"
pillow = "^7.1.1"

[tool.poetry.dev-dependencies]
pytest-randomly = "^3.2.1"
pytest = "^5.4.1"
sphinx = "^3.0.0"
tox = "^3.14.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
